### ISSUE TITLE
Indice.Kentico appending suffix "/connect/authorize"

### ISSUE THREAD

**Issue by epuio** [indice-co/Indice.Kentico#4]
The OIDC URL for my IDP is: 

`https://xyzidp.b2clogin.com/xyzidp.onmicrosoft.com/b2c_1_signin_and_signup/oauth2/v2.0/authorize`

I have configured the following in my settings file: 

`<add key="Oidc:Authority" value="https://xyzidp.b2clogin.com/xyzidp.onmicrosoft.com/b2c_1_signin_and_signup/oauth2/v2.0" />
`
When indice.kentico redirects to the IDP, is uses the following URL:

`https://xyzidp.b2clogin.com/xyzidp.onmicrosoft.com/b2c_1_signin_and_signup/oauth2/v2.0/connect/authorize`

This causes an error on the IDP. Is there a way for me to remove the "connect/" portion of the URL when redirecting to the IDP?

Thank you

**Comment by giorgos07** [comment]
Hi @epuio and thank you for your interest in our library. I added support for a new setting named **Oidc:AuthorizeEndpointPath** (please refer to the README.md file for more) where you can specify your authorize endpoint path. In the near future we will add support for discovering these endpoints from the well known configuration endpoint, so there will be no need for extra settings. If you have any other problem, please let us know.

**Comment by epuio** [comment]
Thank you very much for your very quick response and sorry for my very slow follow up. I appreciate you making that change. Thank you very much!
