### ISSUE TITLE
Updates for authorization code flow

### ISSUE THREAD

**Issue by epuio** [indice-co/Indice.Kentico#6]
Hello,

We are attempting to use AWS Cognito as our identity provider. Cognito doesn't support the hybrid "code id_token". I have made changes to the attached three files in order to get the project to work with Cognito (using the authorization code flow). In the process, I added a few more OAuthConfiguration options for configurability. The code still supports the "code id_token" response_type based on a an OAuthConfiguration option. Here is an example of my web.config configuration:

```
    <add key="Oidc:AutoRedirect" value="false" />
    <add key="Oidc:Authority" value="https://epuio.auth.us-east-2.amazoncognito.com" />
    <add key="Oidc:Host" value="https://test.equio.com/Kentico12" />
    <add key="Oidc:ClientId" value="************" />
    <add key="Oidc:ClientSecret" value="*******" />
    <add key="Oidc:Scopes" value="openid profile" />
    <add key="Oidc:AuthorizeEndpointPath" value="authorize" /> 
    <add key="Oidc:TokenEndpointPath" value="oauth2/token" /> 
    <add key="Oidc:UserInfoEndpointPath" value="oauth2/userInfo" /> 
    <add key="Oidc:ResponseType" value="Code" /> <!-- Allowed values: "Code" or "CodeIdToken" -->
    <add key="Oidc:UserNameClaim" value="username" /> <!-- The name of the claim returned by the IDP that uniquely identifies the user -->
```
[SignInOidcHandler.cs.txt](https://github.com/indice-co/Indice.Kentico/files/7357851/SignInOidcHandler.cs.txt)

I encountered an error where I had to change "SiteCon
[OAuthConfiguration.cs.txt](https://github.com/indice-co/Indice.Kentico/files/7357849/OAuthConfiguration.cs.txt)
[OidcAuthenticationModule.cs.txt](https://github.com/indice-co/Indice.Kentico/files/7357850/OidcAuthenticationModule.cs.txt)
text.CurrentSite.SiteID" to "SiteContext.CurrentSiteID". Not sure why.

I'm not an accomplished programmer so I'm sure there are many things that can be improved in my changes. I couldn't figure out how to create a new branch and push it so I've attached the three files that I changed.

I hope these changes are helpful. I would appreciate any feedback you may have.

Paul

**Comment by epuio** [comment]
I noticed that you replied to my other question but not this one. I apologize that the three files that I dragged and dropped into the message ended up in odd places within the next (didn't realize that was going to happen). I would be interested in understanding whether my suggested changes are helpful. I don't mean to be a nuisance and create more work for you all. Thank you for developing the plugin and making it available. It is very helpful.

**Comment by cleftheris** [comment]
Hi @epuio 

in order to evaluate the changes you are suggesting you should create a fork first. Checkout these instructions here https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
If the changes make sense we could eventualy merge back and publish an updated package.

C.

**Comment by giorgos07** [comment]
Hello @epuio Thank you for your contribution. Your changes in the pull request look good so we released a [new version of the package](https://www.nuget.org/packages/Indice.Kentico.Oidc/12.0.5) that includes your changes. Please let us know if there is anything else we can do to help.

Giorgos

**Comment by epuio** [comment]
Thank you, Giorgos. I'll keep you posted if we make any other changes to the code. Thanks for all of your great work in creating this module. It is very helpful.

Paul
